dist: bionic

language: c

services:
  - docker

script: make

jobs:
  include:
    - env: DOCKER_IMAGE=ubuntu:18.04
    - env: DOCKER_IMAGE=ubuntu:16.04
    - env: DOCKER_IMAGE=debian:buster
    - env: DOCKER_IMAGE=debian:stretch
    - env: DOCKER_IMAGE=debian:jessie
